AWSTemplateFormatVersion: '2010-09-09'


Description: EC2 (Bastion Host)


Parameters:
  ParamCustomerName:
    Type: String

  ParamNotificationEmail:
    Type: String

  ParamVpcStackName:
    Type: String

  ParamAccessKey:
    Type: String

  ParamEC2Tag:
    Type: String

  ParamImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-30041c53

  ParamInstanceType:
    Type: String
    Default: t2.nano
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium


Resources:
  InstanceBastion:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ParamImageId
      InstanceType:
        Ref: ParamInstanceType
      KeyName:
        Ref: ParamAccessKey
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId:
            Fn::ImportValue: !Join [ ":", [ !Ref ParamVpcStackName, SubnetBastion ] ]
          GroupSet:
            - Fn::ImportValue: !Join [ ":", [ !Ref ParamVpcStackName, SecurityGroupMgmt ] ]
      UserData:
        "Fn::Base64": !Sub |
          #cloud-config
          package_upgrade: true
          packages:
            - git
            - tmux
            - telnet
            - tcpdump
            - nfs-utils
          users:
            - default
          write_files:
              - path: /root/.aws/config
                owner: 'root:root'
                permissions: '0600'
                content: |
                  [default]
                  region = ap-southeast-2
              - path: /root/.aws/credentials
                owner: 'root:root'
                permissions: '0600'
                content: |
                  [default]
                  aws_access_key_id =
                  aws_secret_access_key =
          runcmd:
            - [ mkdir, /u01 ]
            - [ mkdir, -p, /opt/hosted/deploy ]
            - [ aws, s3, cp, 's3://deploy-v1/brandsite/include/env.sh', /opt/hosted/deploy/ ]
            - [ aws, s3, cp, 's3://deploy-v1/brandsite/include/userdata-bas.sh', /opt/hosted/deploy/ ]
            - [ chmod, go-x, /opt/hosted/deploy ]
            - [ chmod, ug+x, /opt/hosted/deploy/userdata-bas.sh ]
            - [ /opt/hosted/deploy/userdata-bas.sh ]
            - [ touch, /root/built ]
          power_state:
            delay: "+1"
            mode: reboot
      Tags:
        - Key: Management
          Value: Hosted
        - Key: Name
          Value:
            Ref: ParamEC2Tag
    #DependsOn:
    #  - Fn::ImportValue: !Join [ ":", [ !Ref ParamVpcStackName, VPCGatewayAttachment ] ]
    #  - Fn::ImportValue: !Join [ ":", [ !Ref ParamVpcStackName, FileSystem ] ]


Outputs:
  OutputInstancePublicIpBastion:
    Description: Public address of bastion host of current VPC
    Value: !GetAtt InstanceBastion.PublicIp
    Export:
      Name: !Join [ ":", [ !Ref ParamVpcStackName, OutputInstancePublicIpBastion ] ]

# vim:syntax=yaml tabstop=2 expandtab nowrap:
